services:
  mysql:
    image: mysql:8.0
    container_name: medilink-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medilink
      MYSQL_USER: medilink
      MYSQL_PASSWORD: medilink123
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./infra/sql:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
